---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  customize:
    memory: '512'
transport:
  name: dokken
provisioner:
  name: dokken
  chef_version: 12.21.3
  deprecations_as_errors: true
verifier:
  name: inspec
platforms:
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https net-tools -y
  - name: centos-7
    driver:
      image: centos:7
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum clean all
        - RUN yum -y install net-tools lsof
suites:
  - name: default
    run_list:
      - recipe[nginx-passenger::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
